---
title: "R package containing TCGA data"
author: "Marcin Kosiński"
date: "`r Sys.Date()`"
output: 
   rmarkdown::html_vignette:
      fig_width: 17
      fig_height: 10
      toc: true
      toc_depth: 3
      keep_md: true
      includes:
         in_header: include/in_header.html
         before_body: include/before_body.html
vignette: >
  %\VignetteIndexEntry{home}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
library(knitr)
opts_chunk$set(comment="", message=FALSE, warning = FALSE, tidy.opts=list(keep.blank.line=TRUE, width.cutoff=150),options(width=150), cache=TRUE, eval = FALSE)
```

<h5> Installation of the `RTCGA` package: </h5>
To get started, install the latest version of **RTCGA** from Bioconductor:
```{r}
# not there yet
```
or use:
```{r}
if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
}
install_github("MarcinKosinski/RTCGA")
```
Make sure you have [rtools](http://cran.r-project.org/bin/windows/Rtools/) installed on your computer.


<h5> Installation of the `RTCGA.data` package: </h5>
Install the latest version of **RTCGA.data** from Bioconductor:
```{r}
# not there yet
```
or use:
```{r}
if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
}
install_github("mi2-warsaw/RTCGA.data")
```

<h5> The list of available datasets: </h5>
```{r}
library(RTCGA.data)
?clinical
?rnaseq
```
